workflows:
  flutter:
    name: Flutter Build and Distribute
    max_build_duration: 60
    triggers:
      - push
      - pull_request
    scripts:
      # 1. Checkout source code
      - checkout: true

      # 2. Install dependencies
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      # 3. Build APK (Android)
      - name: Build APK (Android)
        script: |
          flutter build apk --release

      # 4. Build IPA (iOS)
      - name: Build IPA (iOS)
        script: |
          flutter build ios --release

      # 5. Install Firebase CLI
      - name: Install Firebase CLI
        script: |
          npm install -g firebase-tools

      # 6. Upload APK to Firebase App Distribution
      - name: Upload APK to Firebase
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app <YOUR_FIREBASE_APP_ID> \
            --groups testers \
            --token $FIREBASE_CLI_TOKEN

    artifacts:
      # 7. Store build artifacts
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/Runner.ipa
