workflows:
  flutter:
    name: Flutter Build and Distribute
    max_build_duration: 60
    triggers:
      - events:
          - push
          - pull_request
    # Flutter 构建设置
    steps:
      - name: Checkout source code
        code: git clone https://github.com/your-username/your-repo.git
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK (Android)
        flutter:
          target: lib/main.dart
          build_mode: release
          platform: android
      - name: Build IPA (iOS)
        flutter:
          target: lib/main.dart
          build_mode: release
          platform: ios
    scripts:
      - name: Install Firebase CLI
        script: |
          npm install -g firebase-tools
      - name: Firebase App Distribution
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:594502835954:ios:79d3b7f2656fa5ee103a6b \
            --groups testers \
            --token 1//0gjobfWdqtGAECgYIARAAGBASNwF-L9IrDN3h1KJODIh3dd2izYCLQmg-yo_ZapAkUBaKuk4E9slOiPzIULsg0EpS12gMhLSixMg
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/Runner.ipa
