workflows:
  flutter:
    name: Flutter Build and Distribute
    max_build_duration: 60
    triggers:
      - events:
          - push
          - pull_request
    android:
      flutter: true
      build_mode: release
    ios:
      flutter: true
      build_mode: release
    scripts:
      - name: Install Firebase CLI
        script: |
          npm install -g firebase-tools
      - name: Build APK (Android)
        script: |
          flutter build apk --release
      - name: Build IPA (iOS)
        script: |
          flutter build ios --release
      - name: Firebase App Distribution
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:594502835954:ios:79d3b7f2656fa5ee103a6b \
            --groups testers \
            --token 1//0gjobfWdqtGAECgYIARAAGBASNwF-L9IrDN3h1KJODIh3dd2izYCLQmg-yo_ZapAkUBaKuk4E9slOiPzIULsg0EpS12gMhLSixMg
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/Runner.ipa
