workflows:
  flutter_build_and_distribute:
    name: Flutter Build and Distribute
    max_build_duration: 60
    triggers:
      - events:
          - push
          - pull_request

    # 平台配置：Android 和 iOS 构建
    platforms:
      ios:
        build:
          flutter: true
          xcode:
            export_method: ad-hoc
      android:
        build:
          flutter: true

    # Firebase CLI 配置
    scripts:
      - name: Install Firebase CLI
        script: |
          npm install -g firebase-tools

      - name: Upload APK to Firebase
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app <YOUR_FIREBASE_APP_ID> \
            --groups testers \
            --token $FIREBASE_CLI_TOKEN

    # 构建产物
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/Runner.ipa
