 
workflows:
  flutter:
    name: Flutter Build and Distribute
    max_build_duration: 60  # 最大构建时间（分钟）
    triggers:
      - events:
          - push
          - pull_request
    platforms:
      ios:
        build:
          flutter: true
          xcode:
            export_method: ad-hoc  # iOS 应用的发布方法（Ad-hoc 测试）
      android:
        build:
          flutter: true
    scripts:
      - name: Install Firebase CLI
        script: |
          npm install -g firebase-tools  # 安装 Firebase CLI
      - name: Firebase App Distribution
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app 1:594502835954:ios:79d3b7f2656fa5ee103a6b --groups testers --token 1//0gObGeeZ8jNkoCgYIARAAGBASNwF-L9IrMP5gYg5AmzMEJjzHr1KnUMf7-IPaCa5owSRhwnDZiWVtjtqCbgR6Px6fYttNp7254Wc  # 分发 APK 到 Firebase
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk