workflows:
  flutter:
    name: Flutter Build
    max_build_duration: 60
   instance_type: mac_mini_m2
    triggering:
      - events:
          - push
          - pull_request
    scripts:
      - name: Install Firebase CLI
        script: |
          npm install -g firebase-tools
      - name: Firebase App Distribution
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app <YOUR_FIREBASE_APP_ID> --groups testers --token $FIREBASE_CLI_TOKEN
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
