workflows:
  flutter:
    name: Flutter Build and Distribute
    max_build_duration: 60
    triggerring:
      - events:
          - push
          - pull_request
    scripts:
      - name: Checkout source code
        checkout: true
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build APK (Android)
        script: |
          flutter build apk --release
      - name: Build IPA (iOS)
        script: |
          flutter build ios --release
      - name: Install Firebase CLI
        script: |
          npm install -g firebase-tools
      - name: Firebase App Distribution
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app <YOUR_FIREBASE_APP_ID> \
            --groups testers \
            --token $FIREBASE_CLI_TOKEN
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/Runner.ipa
