workflows:
  flutter_build_and_distribute:
    name: Flutter Build and Distribute
    max_build_duration: 60
    triggers:
      - events:
          - push
          - pull_request
    steps:
      - name: Checkout source code
        checkout: true

      # Step 1: Install Flutter dependencies
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      # Step 2: Build APK for Android
      - name: Build APK (Android)
        script: |
          flutter build apk --release

      # Step 3: Build IPA for iOS
      - name: Build IPA (iOS)
        script: |
          flutter build ios --release

      # Step 4: Install Firebase CLI
      - name: Install Firebase CLI
        script: |
          npm install -g firebase-tools

      # Step 5: Upload APK to Firebase App Distribution
      - name: Upload APK to Firebase
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app <YOUR_FIREBASE_APP_ID> \
            --groups testers \
            --token $FIREBASE_CLI_TOKEN

    artifacts:
      # Store the APK and IPA files as build artifacts
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/Runner.ipa
